import { inngest } from "../client";
import { getAnalyticsSummary, getAnomalyAlerts } from "@/lib/dal/analytics";
import { db } from "@/db";

/**
 * F3.1.16: Weekly analytics report — auto-generated by xiaoshu.
 * Runs every Monday at 9:00 AM Beijing time.
 *
 * Creates a data_journalism mission for xiaoshu to produce a weekly report.
 */
export const weeklyAnalyticsReport = inngest.createFunction(
  { id: "weekly-analytics-report", name: "Weekly Analytics Report" },
  { cron: "0 9 * * 1" }, // Every Monday at 9:00 AM
  async ({ step }) => {
    const stats = await step.run("fetch-stats", async () => {
      return getAnalyticsSummary();
    });

    const alerts = await step.run("check-anomalies", async () => {
      return getAnomalyAlerts();
    });

    // Create a mission to generate the weekly report
    await step.run("create-report-mission", async () => {
      const org = await db.query.organizations.findFirst({
        orderBy: (o, { asc }) => [asc(o.createdAt)],
      });
      if (!org) return;

      const weekLabel = new Date().toLocaleDateString("zh-CN", { month: "long", day: "numeric" });
      const { startMissionFromModule } = await import("@/app/actions/missions");
      await startMissionFromModule({
        organizationId: org.id,
        title: `${weekLabel} 周度数据分析报告`,
        scenario: "data_journalism",
        userInstruction: `生成本周全渠道数据分析报告。\n\n当前数据摘要：\n${JSON.stringify(stats, null, 2)}\n\n异常预警数量：${alerts.length}`,
        sourceModule: "analytics",
        sourceEntityType: "scheduled_report",
        sourceContext: { alertCount: alerts.length, period: "weekly" },
      });
    });

    return { reported: true, alertCount: alerts.length };
  }
);
