import { inngest } from "../client";
import { getAnalyticsSummary, getAnomalyAlerts } from "@/lib/dal/analytics";
import { postTeamMessage } from "@/lib/dal/team-messages";

/**
 * F3.1.16: Weekly analytics report — auto-generated by 小数 and posted to team messages.
 * Runs every Monday at 9:00 AM Beijing time.
 */
export const weeklyAnalyticsReport = inngest.createFunction(
  { id: "weekly-analytics-report", name: "Weekly Analytics Report" },
  { cron: "0 9 * * 1" }, // Every Monday at 9:00 AM
  async ({ step }) => {
    const stats = await step.run("fetch-stats", async () => {
      return getAnalyticsSummary();
    });

    const alerts = await step.run("check-anomalies", async () => {
      return getAnomalyAlerts();
    });

    await step.run("post-report", async () => {
      const viewsDisplay =
        stats.totalViews >= 10000
          ? `${(stats.totalViews / 10000).toFixed(1)}万`
          : stats.totalViews.toLocaleString();

      let content = `本周传播效果周报：总阅读 ${viewsDisplay}`;
      content += `（${stats.totalViewsChange > 0 ? "+" : ""}${stats.totalViewsChange}%）`;
      content += `，平均互动率 ${stats.avgEngagement}%`;
      content += `，发布 ${stats.contentPublished} 篇`;
      content += `，爆款率 ${stats.hitRate}%`;

      if (alerts.length > 0) {
        content += `。发现 ${alerts.length} 条数据异常，请关注。`;
      }

      await postTeamMessage({
        senderSlug: "xiaoshu",
        type: "work_output",
        content,
        attachments: [
          {
            type: "chart",
            title: "本周传播效果周报",
            description: `阅读 ${viewsDisplay} | 互动率 ${stats.avgEngagement}% | 发布 ${stats.contentPublished} 篇`,
          },
        ],
      });
    });

    // Post anomaly alerts as separate messages
    if (alerts.length > 0) {
      await step.run("post-anomaly-alerts", async () => {
        for (const alert of alerts) {
          await postTeamMessage({
            senderSlug: "xiaoshu",
            type: "alert",
            content: alert.message,
            attachments: [
              {
                type: "chart",
                title: `${alert.channel} ${alert.metric}异常`,
                description: `当前: ${alert.currentValue} | 均值: ${alert.previousValue} | 变化: ${alert.changePercent}%`,
              },
            ],
          });
        }
      });
    }

    return { reported: true, alertCount: alerts.length };
  }
);
