import { FileText } from "lucide-react";
import {
  SCENARIO_CONFIG,
  ADVANCED_SCENARIO_CONFIG,
  type ScenarioConfig,
  type AdvancedScenarioKey,
  type AdvancedScenarioConfig,
} from "@/lib/constants";

/**
 * Look up the default user-instruction pre-fill text for a legacy scenario
 * slug. UI layer (e.g. missions-client 的 "发起新任务" sheet) should call this
 * instead of reaching into SCENARIO_CONFIG directly, so Phase 3 can delete
 * SCENARIO_CONFIG by only touching this file.
 */
export function getLegacyTemplateInstruction(
  legacyKey: string | null | undefined,
): string | null {
  if (!legacyKey) return null;
  const cfg = SCENARIO_CONFIG[legacyKey];
  return cfg?.templateInstruction ?? null;
}

/**
 * Shape any mission-like object needs to provide for scenario resolution.
 * Compatible with `Mission`, `MissionSummary`, `MissionWithDetails`.
 */
export interface ScenarioResolvable {
  scenario: string;
  title?: string | null;
}

/**
 * Resolve display config for a mission's scenario slug.
 *
 * After B.1, `mission.scenario` may be:
 * - A legacy SCENARIO_CONFIG key (`breaking_news`, ...) — matched in map 1
 * - An ADVANCED_SCENARIO_CONFIG key (`lianghui_coverage`, ...) — matched in map 2
 * - A custom workflow slug (`custom_xxxxxx`) generated by templateToScenarioSlug — falls through to makeFallback()
 *
 * The fallback synthesizes a minimal ScenarioConfig-shaped object so downstream
 * UI (icon/label/color) renders gracefully instead of throwing on undefined.
 *
 * See spec §4.3 and plan Task 14.
 */
export function resolveScenarioConfig(m: ScenarioResolvable): ScenarioConfig {
  const viaScenarioConfig = SCENARIO_CONFIG[m.scenario];
  if (viaScenarioConfig) return viaScenarioConfig;

  const viaAdvanced =
    ADVANCED_SCENARIO_CONFIG[m.scenario as AdvancedScenarioKey];
  if (viaAdvanced) {
    // ADVANCED_SCENARIO_CONFIG has different field names (label vs name, teamMembers vs defaultTeam);
    // project it onto ScenarioConfig shape so downstream code can treat both sources uniformly.
    return projectAdvancedToScenarioConfig(viaAdvanced);
  }

  return makeFallback(m);
}

function projectAdvancedToScenarioConfig(
  adv: AdvancedScenarioConfig
): ScenarioConfig {
  return {
    label: adv.label,
    category: "advanced",
    icon: adv.icon,
    color: adv.color,
    bgColor: adv.bgColor,
    description: adv.description,
    defaultPriority: 1,
    defaultTeam: adv.teamMembers,
    templateInstruction: "",
  };
}

function makeFallback(m: ScenarioResolvable): ScenarioConfig {
  return {
    label: m.title ?? m.scenario ?? "任务",
    category: "custom",
    icon: FileText,
    color: "#6b7280",
    bgColor: "rgba(107,114,128,0.12)",
    description: "",
    defaultPriority: 2,
    defaultTeam: [],
    templateInstruction: "",
  };
}
