import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";

const CHANGELOG_DIR = path.join(process.cwd(), "content/help/changelog");
const OUTPUT = path.join(process.cwd(), "src/lib/help/changelog-meta.ts");

async function main() {
  let mdxFiles: string[] = [];
  try {
    const files = await fs.readdir(CHANGELOG_DIR);
    mdxFiles = files.filter((f) => f.endsWith(".mdx"));
  } catch {
    // changelog 目录不存在 → 输出空 stub,不挂掉(让 implementer/CI 容错)
  }

  type Entry = { slug: string; publishedAt: string; title: string };
  const entries: Entry[] = [];
  for (const f of mdxFiles) {
    const raw = await fs.readFile(path.join(CHANGELOG_DIR, f), "utf-8");
    const { data } = matter(raw);
    if (data.publishedAt && data.title) {
      entries.push({
        slug: f.replace(/\.mdx$/, ""),
        publishedAt: String(data.publishedAt),
        title: String(data.title),
      });
    }
  }
  const sorted = entries.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
  const latest = sorted[0];

  const content = `// AUTO-GENERATED — do not edit. Generated by scripts/build-help-meta.ts.
export const LATEST_CHANGELOG_AT: number = ${latest ? new Date(latest.publishedAt).getTime() : 0};
export const LATEST_CHANGELOG_SLUG: string = ${JSON.stringify(latest?.slug ?? "")};
export const LATEST_CHANGELOG_TITLE: string = ${JSON.stringify(latest?.title ?? "")};
`;
  await fs.writeFile(OUTPUT, content, "utf-8");
  console.log("✓ help changelog meta written:", latest?.slug ?? "(empty)");
}
main().catch((e) => {
  console.error("✗ build-help-meta failed:", e);
  process.exit(1);
});
