#!/usr/bin/env python3
"""
make-migration-idempotent.py
把 drizzle-kit 生成的原始 DDL SQL 文件转换成幂等版本（IF NOT EXISTS / DO blocks）。

用途：让 snapshot catch-up migration 在已应用过相同变更的 DB 上也能安全运行
（全部 DDL 都变 no-op）。同时新环境也能正确创建。

使用：python3 scripts/make-migration-idempotent.py <sql-file>
"""
import sys
import re
from pathlib import Path


def make_idempotent(sql: str) -> str:
    """转换 SQL 为幂等版本。"""

    # 按 drizzle 的 breakpoint 分割 statements
    statements = sql.split("--> statement-breakpoint")

    transformed = []
    for stmt in statements:
        stmt = stmt.strip()
        if not stmt:
            continue
        transformed.append(_transform_statement(stmt))

    return "\n--> statement-breakpoint\n".join(transformed) + "\n"


def _transform_statement(stmt: str) -> str:
    """转换单条 statement。"""

    # CREATE TABLE "X" (...)
    m = re.match(r'CREATE TABLE\s+"([^"]+)"\s*\(', stmt)
    if m:
        return stmt.replace(f'CREATE TABLE "{m.group(1)}"', f'CREATE TABLE IF NOT EXISTS "{m.group(1)}"', 1)

    # ALTER TABLE "X" ADD COLUMN "Y" TYPE ...
    m = re.match(r'ALTER TABLE\s+"([^"]+)"\s+ADD COLUMN\s+"([^"]+)"', stmt)
    if m:
        return stmt.replace(f'ADD COLUMN "{m.group(2)}"', f'ADD COLUMN IF NOT EXISTS "{m.group(2)}"', 1)

    # CREATE [UNIQUE] INDEX "X" ON ...
    m = re.match(r'CREATE (UNIQUE )?INDEX\s+"([^"]+)"', stmt)
    if m:
        unique = m.group(1) or ""
        idx_name = m.group(2)
        return stmt.replace(
            f'CREATE {unique}INDEX "{idx_name}"',
            f'CREATE {unique}INDEX IF NOT EXISTS "{idx_name}"',
            1,
        )

    # ALTER TYPE "X" ADD VALUE 'Y'  或  'Y' BEFORE 'Z'
    m = re.match(r'ALTER TYPE\s+"([^"]+)"(\."[^"]+")?\s+ADD VALUE', stmt)
    if m:
        return stmt.replace("ADD VALUE", "ADD VALUE IF NOT EXISTS", 1)

    # CREATE TYPE "X" AS ENUM (...) → DO block with pg_type check
    m = re.match(r'CREATE TYPE\s+"([^"]+)"\.("[^"]+")\s+AS ENUM\s*\((.*?)\)\s*;?$', stmt, re.DOTALL)
    if m:
        schema = m.group(1)
        type_name_quoted = m.group(2)
        type_name_bare = type_name_quoted.strip('"')
        enum_values = m.group(3).strip()
        return (
            f"DO $$ BEGIN\n"
            f"  IF NOT EXISTS (\n"
            f"    SELECT 1 FROM pg_type t\n"
            f"    JOIN pg_namespace n ON n.oid = t.typnamespace\n"
            f"    WHERE t.typname = '{type_name_bare}' AND n.nspname = '{schema}'\n"
            f"  ) THEN\n"
            f'    CREATE TYPE "{schema}".{type_name_quoted} AS ENUM ({enum_values});\n'
            f"  END IF;\n"
            f"END $$;"
        )
    m = re.match(r'CREATE TYPE\s+("[^"]+")\s+AS ENUM\s*\((.*?)\)\s*;?$', stmt, re.DOTALL)
    if m:
        type_name_quoted = m.group(1)
        type_name_bare = type_name_quoted.strip('"')
        enum_values = m.group(2).strip()
        return (
            f"DO $$ BEGIN\n"
            f"  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{type_name_bare}') THEN\n"
            f"    CREATE TYPE {type_name_quoted} AS ENUM ({enum_values});\n"
            f"  END IF;\n"
            f"END $$;"
        )

    # ALTER TABLE "X" ADD CONSTRAINT "Y" ... → DO block with pg_constraint check
    m = re.match(r'ALTER TABLE\s+"([^"]+)"\s+ADD CONSTRAINT\s+"([^"]+)"\s+(.*)$', stmt, re.DOTALL)
    if m:
        table = m.group(1)
        cons_name = m.group(2)
        cons_body = m.group(3).rstrip(";")
        return (
            f"DO $$ BEGIN\n"
            f"  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '{cons_name}') THEN\n"
            f'    ALTER TABLE "{table}" ADD CONSTRAINT "{cons_name}" {cons_body};\n'
            f"  END IF;\n"
            f"END $$;"
        )

    # DROP TABLE "X" → DROP TABLE IF EXISTS "X"
    m = re.match(r'DROP TABLE\s+"([^"]+)"', stmt)
    if m and "IF EXISTS" not in stmt:
        return stmt.replace(f'DROP TABLE "{m.group(1)}"', f'DROP TABLE IF EXISTS "{m.group(1)}"', 1)

    # DROP INDEX "X" → DROP INDEX IF EXISTS "X"
    m = re.match(r'DROP INDEX\s+"([^"]+)"', stmt)
    if m and "IF EXISTS" not in stmt:
        return stmt.replace(f'DROP INDEX "{m.group(1)}"', f'DROP INDEX IF EXISTS "{m.group(1)}"', 1)

    # 默认：原样返回
    return stmt


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 make-migration-idempotent.py <sql-file>")
        sys.exit(1)

    sql_path = Path(sys.argv[1])
    if not sql_path.exists():
        print(f"File not found: {sql_path}")
        sys.exit(1)

    original = sql_path.read_text(encoding="utf-8")
    transformed = make_idempotent(original)

    # 在头部加注释说明
    header = (
        f"-- {sql_path.name}\n"
        f"-- GENERATED by drizzle-kit + made idempotent by make-migration-idempotent.py\n"
        f"-- 所有 DDL 都是 IF NOT EXISTS / DO block 形式，对已有相同对象的 DB 是 no-op。\n"
        f"-- 新环境从零重建时正确执行所有 CREATE。\n"
        f"\n"
    )

    sql_path.write_text(header + transformed, encoding="utf-8")
    print(f"✓ {sql_path} 已转换为幂等 SQL")


if __name__ == "__main__":
    main()
