-- 0029_catchup_hand_written_migrations.sql
-- GENERATED by drizzle-kit + made idempotent by make-migration-idempotent.py
-- 所有 DDL 都是 IF NOT EXISTS / DO block 形式，对已有相同对象的 DB 是 no-op。
-- 新环境从零重建时正确执行所有 CREATE。

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'cms_publication_state' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."cms_publication_state" AS ENUM ('submitting', 'submitted', 'synced', 'rejected_by_cms', 'failed', 'retrying');
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'review_tier' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."review_tier" AS ENUM ('strict', 'relaxed');
  END IF;
END $$;
--> statement-breakpoint
ALTER TYPE "public"."artifact_type" ADD VALUE IF NOT EXISTS 'cms_publication';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'deep' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'social' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'advanced' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'livelihood' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'podcast' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'drama' BEFORE 'custom';
--> statement-breakpoint
ALTER TYPE "public"."workflow_category" ADD VALUE IF NOT EXISTS 'daily_brief' BEFORE 'custom';
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cms_apps" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"channel_key" text NOT NULL,
	"cms_app_id" text NOT NULL,
	"site_id" integer NOT NULL,
	"name" text NOT NULL,
	"appkey" text,
	"appsecret" text,
	"last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cms_catalogs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"cms_catalog_id" integer NOT NULL,
	"app_id" integer NOT NULL,
	"site_id" integer NOT NULL,
	"name" text NOT NULL,
	"parent_id" integer DEFAULT 0,
	"inner_code" text,
	"alias" text,
	"tree_level" integer,
	"is_leaf" boolean DEFAULT true,
	"catalog_type" integer DEFAULT 1,
	"video_player" text,
	"audio_player" text,
	"live_player" text,
	"vlive_player" text,
	"h5_preview" text,
	"pc_preview" text,
	"url" text,
	"deleted_at" timestamp with time zone,
	"last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cms_channels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"channel_key" text NOT NULL,
	"channel_code" integer NOT NULL,
	"name" text NOT NULL,
	"pick_value" text,
	"third_flag" text,
	"last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cms_sync_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"state" text NOT NULL,
	"stats" jsonb,
	"warnings" jsonb,
	"trigger_source" text,
	"operator_id" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"duration_ms" integer,
	"error_message" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cms_publications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"article_id" uuid NOT NULL,
	"app_channel_slug" text NOT NULL,
	"cms_article_id" text,
	"cms_catalog_id" text,
	"cms_site_id" integer,
	"cms_state" "cms_publication_state" DEFAULT 'submitting' NOT NULL,
	"cms_type" integer,
	"request_hash" text,
	"request_payload" jsonb,
	"response_payload" jsonb,
	"preview_url" text,
	"published_url" text,
	"attempts" integer DEFAULT 0 NOT NULL,
	"error_code" text,
	"error_message" text,
	"operator_id" text,
	"trigger_source" text,
	"scheduled_at" timestamp with time zone,
	"submitted_at" timestamp with time zone,
	"synced_at" timestamp with time zone,
	"last_attempt_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "app_channels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"display_name" text NOT NULL,
	"review_tier" "review_tier" DEFAULT 'relaxed' NOT NULL,
	"default_catalog_id" uuid,
	"default_list_style" jsonb,
	"default_cover_url" text,
	"icon" text,
	"sort_order" integer DEFAULT 0,
	"is_enabled" boolean DEFAULT true,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP TABLE IF EXISTS "employee_scenarios" CASCADE;
--> statement-breakpoint
ALTER TABLE "missions" ADD COLUMN IF NOT EXISTS "workflow_template_id" uuid;
--> statement-breakpoint
ALTER TABLE "missions" ADD COLUMN IF NOT EXISTS "input_params" jsonb DEFAULT '{}'::jsonb NOT NULL;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "icon" text;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "input_fields" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "default_team" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "app_channel_slug" text;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "system_instruction" text;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "legacy_scenario_key" text;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "content" text DEFAULT '';
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "is_public" boolean DEFAULT true NOT NULL;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "owner_employee_id" text;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "launch_mode" text DEFAULT 'form' NOT NULL;
--> statement-breakpoint
ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "prompt_template" text;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_apps_organization_id_organizations_id_fk') THEN
    ALTER TABLE "cms_apps" ADD CONSTRAINT "cms_apps_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_catalogs_organization_id_organizations_id_fk') THEN
    ALTER TABLE "cms_catalogs" ADD CONSTRAINT "cms_catalogs_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_channels_organization_id_organizations_id_fk') THEN
    ALTER TABLE "cms_channels" ADD CONSTRAINT "cms_channels_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_sync_logs_organization_id_organizations_id_fk') THEN
    ALTER TABLE "cms_sync_logs" ADD CONSTRAINT "cms_sync_logs_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_publications_organization_id_organizations_id_fk') THEN
    ALTER TABLE "cms_publications" ADD CONSTRAINT "cms_publications_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cms_publications_article_id_articles_id_fk') THEN
    ALTER TABLE "cms_publications" ADD CONSTRAINT "cms_publications_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'app_channels_organization_id_organizations_id_fk') THEN
    ALTER TABLE "app_channels" ADD CONSTRAINT "app_channels_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'app_channels_default_catalog_id_cms_catalogs_id_fk') THEN
    ALTER TABLE "app_channels" ADD CONSTRAINT "app_channels_default_catalog_id_cms_catalogs_id_fk" FOREIGN KEY ("default_catalog_id") REFERENCES "public"."cms_catalogs"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "cms_apps_org_appid_uniq" ON "cms_apps" USING btree ("organization_id","cms_app_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_apps_site_id_idx" ON "cms_apps" USING btree ("organization_id","site_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "cms_catalogs_org_catid_uniq" ON "cms_catalogs" USING btree ("organization_id","cms_catalog_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_catalogs_tree_idx" ON "cms_catalogs" USING btree ("organization_id","parent_id","deleted_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_catalogs_app_idx" ON "cms_catalogs" USING btree ("organization_id","app_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "cms_channels_org_key_uniq" ON "cms_channels" USING btree ("organization_id","channel_key");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_sync_logs_org_time_idx" ON "cms_sync_logs" USING btree ("organization_id","started_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_pub_article_idx" ON "cms_publications" USING btree ("article_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_pub_cms_article_idx" ON "cms_publications" USING btree ("cms_article_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_pub_org_state_idx" ON "cms_publications" USING btree ("organization_id","cms_state");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cms_pub_channel_state_idx" ON "cms_publications" USING btree ("app_channel_slug","cms_state");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "app_channels_org_slug_uniq" ON "app_channels" USING btree ("organization_id","slug");
