-- 0030_workflow_templates_featured.sql
-- GENERATED by drizzle-kit + made idempotent by make-migration-idempotent.py
-- 所有 DDL 都是 IF NOT EXISTS / DO block 形式，对已有相同对象的 DB 是 no-op。
-- 新环境从零重建时正确执行所有 CREATE。

ALTER TABLE "workflow_templates" ADD COLUMN IF NOT EXISTS "is_featured" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_templates_org_legacy_key_uidx" ON "workflow_templates" USING btree ("organization_id","legacy_scenario_key") WHERE "workflow_templates"."legacy_scenario_key" IS NOT NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "workflow_templates_org_builtin_name_uidx" ON "workflow_templates" USING btree ("organization_id","name") WHERE "workflow_templates"."is_builtin" = true AND "workflow_templates"."legacy_scenario_key" IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_workflow_templates_featured" ON "workflow_templates" USING btree ("organization_id","is_featured") WHERE "workflow_templates"."is_featured" = true AND "workflow_templates"."is_public" = true;
