-- 0039_catchup_drift_snapshot_sync.sql
-- GENERATED by drizzle-kit + made idempotent by make-migration-idempotent.py
-- 所有 DDL 都是 IF NOT EXISTS / DO block 形式，对已有相同对象的 DB 是 no-op。
-- 新环境从零重建时正确执行所有 CREATE。

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'account_report_status' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."account_report_status" AS ENUM ('pending', 'crawling', 'scoring', 'analyzing', 'ready', 'failed');
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'account_report_type' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."account_report_type" AS ENUM ('daily', 'weekly', 'monthly', 'custom');
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'account_source' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."account_source" AS ENUM ('my', 'benchmark');
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'article_process_status' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."article_process_status" AS ENUM ('processing', 'done', 'failed');
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'article_source_type' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "public"."article_source_type" AS ENUM ('original', 'repost');
  END IF;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "research_collected_item_districts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"collected_item_id" uuid NOT NULL,
	"district_id" uuid NOT NULL,
	"match_type" "research_topic_match_type" NOT NULL,
	"matched_keyword" text,
	"annotated_by" text DEFAULT 'system' NOT NULL,
	"annotated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "research_cid_unique" UNIQUE("collected_item_id","district_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "research_collected_item_topics" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"collected_item_id" uuid NOT NULL,
	"topic_id" uuid NOT NULL,
	"match_type" "research_topic_match_type" NOT NULL,
	"matched_keyword" text,
	"match_score" numeric(5, 4),
	"annotated_by" text DEFAULT 'system' NOT NULL,
	"annotated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "research_cit_unique" UNIQUE("collected_item_id","topic_id","match_type")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "research_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"source_type" text DEFAULT 'advanced_search' NOT NULL,
	"search_snapshot" jsonb NOT NULL,
	"title" text NOT NULL,
	"topic_description" text,
	"report_html" text,
	"aggregates_json" jsonb,
	"word_file_url" text,
	"excel_file_url" text,
	"file_expires_at" timestamp with time zone,
	"parent_report_id" uuid,
	"is_snapshot" boolean DEFAULT false NOT NULL,
	"snapshot_name" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"current_step" text,
	"error_message" text,
	"generated_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "collected_item_contents" (
	"item_id" uuid PRIMARY KEY NOT NULL,
	"content" text NOT NULL,
	"ocr_text" text,
	"asr_text" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "external_publications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"article_id" uuid NOT NULL,
	"ayrshare_post_id" text,
	"platform" text NOT NULL,
	"platform_post_id" text,
	"platform_post_url" text,
	"status" text DEFAULT 'submitting' NOT NULL,
	"error_code" text,
	"error_message" text,
	"request_payload" jsonb,
	"raw_response" jsonb,
	"operator_id" text,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "article_channel_variants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"article_id" uuid NOT NULL,
	"platform" text NOT NULL,
	"title" text NOT NULL,
	"body" text,
	"summary" text,
	"cover_image_url" text,
	"hashtags" jsonb DEFAULT '[]'::jsonb,
	"extra_fields" jsonb DEFAULT '{}'::jsonb,
	"status" text DEFAULT 'draft' NOT NULL,
	"generated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account_analytics_reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"account_source" "account_source" NOT NULL,
	"account_name_snapshot" text NOT NULL,
	"platform" text NOT NULL,
	"report_type" "account_report_type" DEFAULT 'daily' NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"status" "account_report_status" DEFAULT 'pending' NOT NULL,
	"kpis" jsonb DEFAULT '{"videos":0,"likes":0,"comments":0,"favorites":0,"shares":0}'::jsonb NOT NULL,
	"top_post_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"patterns" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"recommendations" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"executive_summary" text,
	"composite_score_formula_snapshot" jsonb,
	"generated_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_reports_acc_period_type_uniq" UNIQUE("organization_id","account_id","period_start","period_end","report_type")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account_daily_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"account_source" "account_source" NOT NULL,
	"platform" text NOT NULL,
	"snapshot_date" date NOT NULL,
	"post_count" integer DEFAULT 0 NOT NULL,
	"total_likes" integer DEFAULT 0 NOT NULL,
	"total_comments" integer DEFAULT 0 NOT NULL,
	"total_shares" integer DEFAULT 0 NOT NULL,
	"total_views" integer DEFAULT 0 NOT NULL,
	"total_favorites" integer DEFAULT 0 NOT NULL,
	"composite_score_total" real DEFAULT 0 NOT NULL,
	"composite_score_avg" real DEFAULT 0 NOT NULL,
	"top_post_id" uuid,
	"raw_metrics" jsonb,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_daily_snapshots_acc_date_uniq" UNIQUE("organization_id","account_id","snapshot_date")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "viral_content_attributions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_id" uuid NOT NULL,
	"collected_item_id" uuid NOT NULL,
	"rank" integer NOT NULL,
	"composite_score" real DEFAULT 0 NOT NULL,
	"primary_tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"secondary_tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"why_viral_summary" text NOT NULL,
	"attribution_markdown" text NOT NULL,
	"dimension_breakdown" jsonb,
	"ai_model_used" text,
	"ai_prompt_version" text,
	"analyzed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "viral_attributions_report_rank_uniq" UNIQUE("report_id","rank")
);
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'research_tasks') THEN
    ALTER TABLE "research_tasks" DISABLE ROW LEVEL SECURITY;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'research_news_article_topic_hits') THEN
    ALTER TABLE "research_news_article_topic_hits" DISABLE ROW LEVEL SECURITY;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'research_news_articles') THEN
    ALTER TABLE "research_news_articles" DISABLE ROW LEVEL SECURITY;
  END IF;
END $$;
--> statement-breakpoint
DROP TABLE IF EXISTS "research_tasks" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "research_news_article_topic_hits" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "research_news_articles" CASCADE;
--> statement-breakpoint
DROP INDEX IF EXISTS "collected_items_org_category_idx";
--> statement-breakpoint
DROP INDEX IF EXISTS "collected_items_content_trgm";
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "collected_items" ALTER COLUMN "category" SET DATA TYPE text[];
EXCEPTION WHEN others THEN
  RAISE NOTICE 'SET DATA TYPE skipped for collected_items.category: %', SQLERRM;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "collected_items" ALTER COLUMN "category" SET DEFAULT ARRAY[]::text[];
EXCEPTION WHEN others THEN
  RAISE NOTICE 'ALTER COLUMN SET DEFAULT ARRAY[]::text[] skipped for collected_items.category: %', SQLERRM;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "collected_items" ALTER COLUMN "category" SET NOT NULL;
EXCEPTION WHEN others THEN
  RAISE NOTICE 'ALTER COLUMN SET NOT NULL skipped for collected_items.category: %', SQLERRM;
END $$;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "language" text DEFAULT 'zh' NOT NULL;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "translated_from_topic_id" uuid;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "external_publish_status" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "source_type" "article_source_type" DEFAULT 'original' NOT NULL;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "source_name" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "source_url" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "source_icon_url" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "ai_analysis_status" "article_process_status";
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "transcoding_status" "article_process_status";
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "keywords" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "cover_image_url" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "share_image_url" text;
--> statement-breakpoint
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "list_style" text;
--> statement-breakpoint
ALTER TABLE "benchmark_accounts" ADD COLUMN IF NOT EXISTS "crawl_cron_enabled" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "benchmark_accounts" ADD COLUMN IF NOT EXISTS "outlet_id" uuid;
--> statement-breakpoint
ALTER TABLE "benchmark_posts" ADD COLUMN IF NOT EXISTS "aigc_content_category" text;
--> statement-breakpoint
ALTER TABLE "benchmark_posts" ADD COLUMN IF NOT EXISTS "aigc_keywords" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "benchmark_posts" ADD COLUMN IF NOT EXISTS "aigc_annotated_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "benchmark_posts" ADD COLUMN IF NOT EXISTS "aigc_annotation_model" text;
--> statement-breakpoint
ALTER TABLE "my_accounts" ADD COLUMN IF NOT EXISTS "crawl_cron_enabled" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "my_accounts" ADD COLUMN IF NOT EXISTS "outlet_id" uuid;
--> statement-breakpoint
ALTER TABLE "my_posts" ADD COLUMN IF NOT EXISTS "aigc_content_category" text;
--> statement-breakpoint
ALTER TABLE "my_posts" ADD COLUMN IF NOT EXISTS "aigc_keywords" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint
ALTER TABLE "my_posts" ADD COLUMN IF NOT EXISTS "aigc_annotated_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "my_posts" ADD COLUMN IF NOT EXISTS "aigc_annotation_model" text;
--> statement-breakpoint
ALTER TABLE "research_topics" ADD COLUMN IF NOT EXISTS "group_name" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "external_id" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "platform" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "author" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "account_id" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "account_handle" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "author_follower_count" integer;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "sentiment" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "info_type" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "like_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "comment_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "share_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "view_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "favorite_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "reply_count" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "ip_region" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "post_region" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "mentioned_regions" text[];
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "matched_keywords" text[];
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "matched_regions" text[];
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "industries" text[];
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "cover_image_url" text;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "duration_seconds" integer;
--> statement-breakpoint
ALTER TABLE "collected_items" ADD COLUMN IF NOT EXISTS "composite_score" real DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "media_outlet_dictionary" ADD COLUMN IF NOT EXISTS "group_name" text;
--> statement-breakpoint
ALTER TABLE "media_outlet_dictionary" ADD COLUMN IF NOT EXISTS "channels" jsonb DEFAULT '[]'::jsonb NOT NULL;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_collected_item_districts_collected_item_id_collected_items_id_fk') THEN
    ALTER TABLE "research_collected_item_districts" ADD CONSTRAINT "research_collected_item_districts_collected_item_id_collected_items_id_fk" FOREIGN KEY ("collected_item_id") REFERENCES "public"."collected_items"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_collected_item_districts_district_id_research_cq_districts_id_fk') THEN
    ALTER TABLE "research_collected_item_districts" ADD CONSTRAINT "research_collected_item_districts_district_id_research_cq_districts_id_fk" FOREIGN KEY ("district_id") REFERENCES "public"."research_cq_districts"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_collected_item_topics_collected_item_id_collected_items_id_fk') THEN
    ALTER TABLE "research_collected_item_topics" ADD CONSTRAINT "research_collected_item_topics_collected_item_id_collected_items_id_fk" FOREIGN KEY ("collected_item_id") REFERENCES "public"."collected_items"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_collected_item_topics_topic_id_research_topics_id_fk') THEN
    ALTER TABLE "research_collected_item_topics" ADD CONSTRAINT "research_collected_item_topics_topic_id_research_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."research_topics"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_reports_organization_id_organizations_id_fk') THEN
    ALTER TABLE "research_reports" ADD CONSTRAINT "research_reports_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_reports_parent_report_id_research_reports_id_fk') THEN
    ALTER TABLE "research_reports" ADD CONSTRAINT "research_reports_parent_report_id_research_reports_id_fk" FOREIGN KEY ("parent_report_id") REFERENCES "public"."research_reports"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'research_reports_generated_by_user_profiles_id_fk') THEN
    ALTER TABLE "research_reports" ADD CONSTRAINT "research_reports_generated_by_user_profiles_id_fk" FOREIGN KEY ("generated_by") REFERENCES "public"."user_profiles"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'collected_item_contents_item_id_collected_items_id_fk') THEN
    ALTER TABLE "collected_item_contents" ADD CONSTRAINT "collected_item_contents_item_id_collected_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."collected_items"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'external_publications_organization_id_organizations_id_fk') THEN
    ALTER TABLE "external_publications" ADD CONSTRAINT "external_publications_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'external_publications_article_id_articles_id_fk') THEN
    ALTER TABLE "external_publications" ADD CONSTRAINT "external_publications_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'article_channel_variants_organization_id_organizations_id_fk') THEN
    ALTER TABLE "article_channel_variants" ADD CONSTRAINT "article_channel_variants_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'article_channel_variants_article_id_articles_id_fk') THEN
    ALTER TABLE "article_channel_variants" ADD CONSTRAINT "article_channel_variants_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_analytics_reports_organization_id_organizations_id_fk') THEN
    ALTER TABLE "account_analytics_reports" ADD CONSTRAINT "account_analytics_reports_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_daily_snapshots_organization_id_organizations_id_fk') THEN
    ALTER TABLE "account_daily_snapshots" ADD CONSTRAINT "account_daily_snapshots_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_daily_snapshots_top_post_id_collected_items_id_fk') THEN
    ALTER TABLE "account_daily_snapshots" ADD CONSTRAINT "account_daily_snapshots_top_post_id_collected_items_id_fk" FOREIGN KEY ("top_post_id") REFERENCES "public"."collected_items"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viral_content_attributions_report_id_account_analytics_reports_id_fk') THEN
    ALTER TABLE "viral_content_attributions" ADD CONSTRAINT "viral_content_attributions_report_id_account_analytics_reports_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."account_analytics_reports"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viral_content_attributions_collected_item_id_collected_items_id_fk') THEN
    ALTER TABLE "viral_content_attributions" ADD CONSTRAINT "viral_content_attributions_collected_item_id_collected_items_id_fk" FOREIGN KEY ("collected_item_id") REFERENCES "public"."collected_items"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_cid_item_idx" ON "research_collected_item_districts" USING btree ("collected_item_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_cid_district_idx" ON "research_collected_item_districts" USING btree ("district_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_cit_item_idx" ON "research_collected_item_topics" USING btree ("collected_item_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_cit_topic_idx" ON "research_collected_item_topics" USING btree ("topic_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_reports_org_idx" ON "research_reports" USING btree ("organization_id","created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_reports_parent_idx" ON "research_reports" USING btree ("parent_report_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_item_contents_content_trgm" ON "collected_item_contents" USING gin ("content" gin_trgm_ops);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_item_contents_ocr_trgm" ON "collected_item_contents" USING gin ("ocr_text" gin_trgm_ops) WHERE ocr_text IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_item_contents_asr_trgm" ON "collected_item_contents" USING gin ("asr_text" gin_trgm_ops) WHERE asr_text IS NOT NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ext_pub_article_idx" ON "external_publications" USING btree ("article_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ext_pub_ayrshare_idx" ON "external_publications" USING btree ("ayrshare_post_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ext_pub_org_platform_status_idx" ON "external_publications" USING btree ("organization_id","platform","status");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "acv_article_platform_uidx" ON "article_channel_variants" USING btree ("article_id","platform");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "acv_org_article_idx" ON "article_channel_variants" USING btree ("organization_id","article_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_account_reports_org_generated" ON "account_analytics_reports" USING btree ("organization_id","generated_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_account_reports_account_generated" ON "account_analytics_reports" USING btree ("account_id","generated_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_account_daily_snapshots_org_date" ON "account_daily_snapshots" USING btree ("organization_id","snapshot_date");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_account_daily_snapshots_account_date" ON "account_daily_snapshots" USING btree ("account_id","snapshot_date");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_viral_attributions_report" ON "viral_content_attributions" USING btree ("report_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_viral_attributions_item" ON "viral_content_attributions" USING btree ("collected_item_id");
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'articles_translated_from_topic_id_hot_topics_id_fk') THEN
    ALTER TABLE "articles" ADD CONSTRAINT "articles_translated_from_topic_id_hot_topics_id_fk" FOREIGN KEY ("translated_from_topic_id") REFERENCES "public"."hot_topics"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "benchmark_posts_aigc_category_idx" ON "benchmark_posts" USING btree ("benchmark_account_id","aigc_content_category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "benchmark_posts_aigc_keywords_gin" ON "benchmark_posts" USING gin ("aigc_keywords");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "benchmark_posts_aigc_annotated_at_idx" ON "benchmark_posts" USING btree ("aigc_annotated_at") WHERE aigc_annotated_at IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "my_posts_aigc_category_idx" ON "my_posts" USING btree ("organization_id","aigc_content_category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "my_posts_aigc_keywords_gin" ON "my_posts" USING gin ("aigc_keywords");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "my_posts_aigc_annotated_at_idx" ON "my_posts" USING btree ("aigc_annotated_at") WHERE aigc_annotated_at IS NULL;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "research_topics_org_group_idx" ON "research_topics" USING btree ("organization_id","group_name");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_first_seen_idx" ON "collected_items" USING btree ("organization_id","first_seen_at" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_category_gin" ON "collected_items" USING gin ("category");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_industries_gin" ON "collected_items" USING gin ("industries");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_mentioned_regions_gin" ON "collected_items" USING gin ("mentioned_regions");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_matched_keywords_gin" ON "collected_items" USING gin ("matched_keywords");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_matched_regions_gin" ON "collected_items" USING gin ("matched_regions");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_author_idx" ON "collected_items" USING btree ("organization_id","author");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_account_idx" ON "collected_items" USING btree ("organization_id","account_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_platform_idx" ON "collected_items" USING btree ("organization_id","platform");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_sentiment_idx" ON "collected_items" USING btree ("organization_id","sentiment");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_ip_region_idx" ON "collected_items" USING btree ("organization_id","ip_region");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_post_region_idx" ON "collected_items" USING btree ("organization_id","post_region");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_external_id_idx" ON "collected_items" USING btree ("organization_id","external_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_like_idx" ON "collected_items" USING btree ("organization_id","like_count" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "collected_items_org_composite_idx" ON "collected_items" USING btree ("organization_id","composite_score" DESC);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "media_outlet_dictionary_group_idx" ON "media_outlet_dictionary" USING btree ("organization_id","group_name");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "media_outlet_dictionary_channels_gin" ON "media_outlet_dictionary" USING gin ("channels" jsonb_path_ops);
--> statement-breakpoint
ALTER TABLE "collected_items" DROP COLUMN IF EXISTS "content";
--> statement-breakpoint
ALTER TABLE "collection_sources" DROP COLUMN IF EXISTS "research_bridge_enabled";
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'research_news_source_channel' AND n.nspname = 'public'
  ) THEN
    DROP TYPE "public"."research_news_source_channel";
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'research_dedup_level' AND n.nspname = 'public'
  ) THEN
    DROP TYPE "public"."research_dedup_level";
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'research_task_status' AND n.nspname = 'public'
  ) THEN
    DROP TYPE "public"."research_task_status";
  END IF;
END $$;
