-- 0040_articles_add_metadata.sql
-- GENERATED by drizzle-kit + made idempotent by make-migration-idempotent.py
-- 所有 DDL 都是 IF NOT EXISTS / DO block 形式，对已有相同对象的 DB 是 no-op。
-- 新环境从零重建时正确执行所有 CREATE。

ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
