// AUTO-GENERATED — do not edit. Generated by scripts/build-help-meta.ts.
export const LATEST_CHANGELOG_AT: number = 1780185600000;
export const LATEST_CHANGELOG_SLUG: string = "2026-05";
export const LATEST_CHANGELOG_TITLE: string = "2026 年 5 月更新";
